package ru.toyota.cars;

@SuppressWarnings("SpellCheckingInspection")
public enum Country {

    Andorra("Андорра"),
    UnitedArabEmirates("ОАЭ"),
    Afghanistan("Афганистан"),
    AntiguaAndBarbuda("Антигуа и Барбуда"),
    Anguilla("Ангилья"),
    Albania("Албания"),
    Armenia("Армения"),
    Angola("Ангола"),
    Antarctica("Антарктика"),
    Argentina("Аргентина"),
    AmericanSamoa("Американское Самоа"),
    Austria("Австрия"),
    Australia("Австралия"),
    Aruba("Аруба"),
    AlandIslands("Аландские острова"),
    Azerbaijan("Азербайджан"),
    BosniaAndHerzegovina("Босния и Герцеговина"),
    Barbados("Барбадос"),
    Bangladesh("Бангладеш"),
    Belgium("Бельгия"),
    BurkinaFaso("Буркина-Фасо"),
    Bulgaria("Болгария"),
    Bahrain("Бахрейн"),
    Burundi("Бурунди"),
    Benin("Бенин"),
    SaintBarthelemy("Сен-Бартелеми"),
    Bermuda("Бермуды"),
    BruneiDarussalam("Бруней"),
    Bolivia("Боливия"),
    BonaireSintEustatiusAndSaba("Бонайре, Синт-Эстатиус и Саба"),
    Brazil("Бразилия"),
    Bahamas("Багамские Острова"),
    Bhutan("Бутан"),
    BouvetIsland("Остров Буве"),
    Botswana("Ботсвана"),
    Belarus("Белоруссия"),
    Belize("Белиз"),
    Canada("Канада"),
    CocosIslands("Кокосовые острова"),
    CongoDemocraticRepublic("ДР Конго"),
    CentralAfricanRepublic("ЦАР"),
    Congo("Республика Конго"),
    Switzerland("Швейцария"),
    CoteDIvoire("Кот-д'Ивуар"),
    CookIslands("Острова Кука"),
    Chile("Чили"),
    Cameroon("Камерун"),
    China("Китай (Китайская Народная Республика)"),
    Colombia("Колумбия"),
    CostaRica("Коста-Рика"),
    Cuba("Куба"),
    CaboVerde("Кабо-Верде"),
    Curacao("Кюрасао"),
    ChristmasIsland("Остров Рождества"),
    Cyprus("Кипр"),
    Czechia("Чехия"),
    Germany("Германия"),
    Djibouti("Джибути"),
    Denmark("Дания"),
    Dominica("Доминика"),
    DominicanRepublic("Доминиканская Республика"),
    Algeria("Алжир"),
    Ecuador("Эквадор"),
    Estonia("Эстония"),
    Egypt("Египет"),
    WesternSahara("САДР"),
    Eritrea("Эритрея"),
    Spain("Испания"),
    Ethiopia("Эфиопия"),
    Finland("Финляндия"),
    Fiji("Фиджи"),
    FalklandIslands("Фолклендские острова"),
    Micronesia("Микронезия"),
    FaroeIslands("Фарерские острова"),
    France("Франция"),
    Gabon("Габон"),
    UnitedKingdom("Великобритания"),
    Grenada("Гренада"),
    Georgia("Грузия"),
    FrenchGuiana("Гвиана"),
    Guernsey("Гернси"),
    Ghana("Гана"),
    Gibraltar("Гибралтар"),
    Greenland("Гренландия"),
    Gambia("Гамбия"),
    Guinea("Гвинея"),
    Guadeloupe("Гваделупа"),
    EquatorialGuinea("Экваториальная Гвинея"),
    Greece("Греция"),
    SouthGeorgiaAndSouthSandwichIslands("Южная Георгия и Южные Сандвичевы Острова"),
    Guatemala("Гватемала"),
    Guam("Гуам"),
    GuineaBissau("Гвинея-Бисау"),
    Guyana("Гайана"),
    HongKong("Гонконг"),
    HeardIslandAndMcDonaldIslands("Херд и Макдональд"),
    Honduras("Гондурас"),
    Croatia("Хорватия"),
    Haiti("Гаити"),
    Hungary("Венгрия"),
    Indonesia("Индонезия"),
    Ireland("Ирландия"),
    Israel("Израиль"),
    IsleOfMan("Остров Мэн"),
    India("Индия"),
    BritishIndianOceanTerritory("Британская Территория в Индийском Океане"),
    Iraq("Ирак"),
    Iran("Иран"),
    Iceland("Исландия"),
    Italy("Италия"),
    Jersey("Джерси"),
    Jamaica("Ямайка"),
    Jordan("Иордания"),
    Japan("Япония"),
    Kenya("Кения"),
    Kyrgyzstan("Киргизия"),
    Cambodia("Камбоджа"),
    Kiribati("Кирибати"),
    Comoros("Коморы"),
    SaintKittsAndNevis("Сент-Китс и Невис"),
    KoreaDemocraticPeopleRepublic("КНДР (Корейская Народно-Демократическая Республика)"),
    KoreaRepublic("Республика Корея"),
    Kuwait("Кувейт"),
    CaymanIslands("Острова Кайман"),
    Kazakhstan("Казахстан"),
    LaoPeoplesDemocraticRepublic("Лаос"),
    Lebanon("Ливан"),
    SaintLucia("Сент-Люсия"),
    Liechtenstein("Лихтенштейн"),
    SriLanka("Шри-Ланка"),
    Liberia("Либерия"),
    Lesotho("Лесото"),
    Lithuania("Литва"),
    Luxembourg("Люксембург"),
    Latvia("Латвия"),
    Libya("Ливия"),
    Morocco("Марокко"),
    Monaco("Монако"),
    Moldova("Молдавия"),
    Montenegro("Черногория"),
    SaintMartin("Сен-Мартен"),
    Madagascar("Мадагаскар"),
    MarshallIslands("Маршалловы Острова"),
    NorthMacedonia("Северная Македония"),
    Mali("Мали"),
    Myanmar("Мьянма"),
    Mongolia("Монголия"),
    Macao("Макао"),
    NorthernMarianaIslands("Северные Марианские Острова"),
    Martinique("Мартиника"),
    Mauritania("Мавритания"),
    Montserrat("Монтсеррат"),
    Malta("Мальта"),
    Mauritius("Маврикий"),
    Maldives("Мальдивы"),
    Malawi("Малави"),
    Mexico("Мексика"),
    Malaysia("Малайзия"),
    Mozambique("Мозамбик"),
    Namibia("Намибия"),
    NewCaledonia("Новая Каледония"),
    Niger("Нигер"),
    NorfolkIsland("Остров Норфолк"),
    Nigeria("Нигерия"),
    Nicaragua("Никарагуа"),
    NetherlandsKingdom("Нидерланды"),
    Norway("Норвегия"),
    Nepal("Непал"),
    Nauru("Науру"),
    Niue("Ниуэ"),
    NewZealand("Новая Зеландия"),
    Oman("Оман"),
    Panama("Панама"),
    Peru("Перу"),
    FrenchPolynesia("Французская Полинезия"),
    PapuaNewGuinea("Папуа — Новая Гвинея"),
    Philippines("Филиппины"),
    Pakistan("Пакистан"),
    Poland("Польша"),
    SaintPierreAndMiquelon("Сен-Пьер и Микелон"),
    Pitcairn("Острова Питкэрн"),
    PuertoRico("Пуэрто-Рико"),
    Palestine("Государство Палестина"),
    Portugal("Португалия"),
    Palau("Палау"),
    Paraguay("Парагвай"),
    Qatar("Катар"),
    Reunion("Реюньон"),
    Romania("Румыния"),
    Serbia("Сербия"),
    RussianFederation("Россия"),
    Rwanda("Руанда"),
    SaudiArabia("Саудовская Аравия"),
    SolomonIslands("Соломоновы Острова"),
    Seychelles("Сейшельские Острова"),
    Sudan("Судан"),
    Sweden("Швеция"),
    Singapore("Сингапур"),
    SaintHelenaAscensionAndTristanDaCunha("Остров Святой Елены"),
    Slovenia("Словения"),
    SvalbardAndJanMayen("Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен"),
    Slovakia("Словакия"),
    SierraLeone("Сьерра-Леоне"),
    SanMarino("Сан-Марино"),
    Senegal("Сенегал"),
    Somalia("Сомали"),
    Suriname("Суринам"),
    SouthSudan("Южный Судан"),
    SaoTomeAndPrincipe("Сан-Томе и Принсипи"),
    ElSalvador("Сальвадор"),
    SintMaarten("Синт-Мартен"),
    SyrianArabRepublic("Сирия"),
    Eswatini("Эсватини"),
    TurksandCaicosIslands("Теркс и Кайкос"),
    Chad("Чад"),
    FrenchSouthernTerritories("Французские Южные и Антарктические территории"),
    Togo("Того"),
    Thailand("Таиланд"),
    Tajikistan("Таджикистан"),
    Tokelau("Токелау"),
    TimorLeste("Восточный Тимор"),
    Turkmenistan("Туркменистан"),
    Tunisia("Тунис"),
    Tonga("Тонга"),
    Turkiye("Турция"),
    TrinidadAndTobago("Тринидад и Тобаго"),
    Tuvalu("Тувалу"),
    Taiwan("Китайская Республика"),
    Tanzania("Танзания"),
    Ukraine("Украина"),
    Uganda("Уганда"),
    UnitedStatesMinorOutlyingIslands("Внешние малые острова США"),
    UnitedStatesOfAmerica("США"),
    Uruguay("Уругвай"),
    Uzbekistan("Узбекистан"),
    HolySee("Ватикан"),
    SaintVincentAndTheGrenadines("Сент-Винсент и Гренадины"),
    Venezuela("Венесуэла"),
    VirginIslandsBritish("Виргинские Острова (Великобритания)"),
    VirginIslandsUSA("Виргинские Острова (США)"),
    VietNam("Вьетнам"),
    Vanuatu("Вануату"),
    WallisAndFutuna("Уоллис и Футуна"),
    Samoa("Самоа"),
    Yemen("Йемен"),
    Mayotte("Майотта"),
    SouthAfrica("ЮАР"),
    Zambia("Замбия"),
    Zimbabwe("Зимбабве");

    private final String nameRus;

    Country(String nameRus) {
        this.nameRus = nameRus;
    }

    @Override
    public String toString() {
        return nameRus;
    }
}
